server:
  port: 8081

spring:
  application.name: bestProduct
  data:
    mongodb:
      host: localhost
      port: 27017
      database: best-product

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.orm.jdbc.bind: trace

#springdoc swagger
springdoc:
  api-docs:
    path: /docs # ?? path ??

  swagger-ui:
    path: /swagger-ui # ?? path ??
    display-request-duration: true
