spring:
  application.name: web-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 'http://localhost:3000'
            allow-credentials: true
            allowed-headers: '*'
            allowed-methods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - name: LoggingFilter
          args:
            baseMessage: Spring Cloud Gateway Filter
            preLogger: true
            postLogger: true

      routes:
        - id: member-api-get
          uri: http://localhost:8082/
          predicates:
            - Path=/member-api/**
            - Method=GET
          filters:
            - RewritePath=/member-api/(?<servicePath>.*), /api/$\{servicePath}
            - AuthorizationHeaderFilter
        - id: member-api-login
          uri: http://localhost:8082/
          predicates:
            - Path=/member-api/login
            - Method=POST, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-api/(?<servicePath>.*), //$\{servicePath}
        - id: member-api-post
          uri: http://localhost:8082/
          predicates:
            - Path=/member-api/**
            - Method=POST
          filters:
            - RewritePath=/member-api/(?<servicePath>.*), /api/$\{servicePath}

        - id: product-api
          uri: http://localhost:8084/
          predicates:
            - Path=/product-api/**
          filters:
            - RewritePath=/product-api/(?<servicePath>.*), /api/$\{servicePath}
            #- AuthorizationHeaderFilter

### jwt
security.jwt:
  secret-key: secret_key
  expiration-time: 86400000


### logging
logging:
  level:
    org.springframework.cloud.gateway: trace
    reactor.netty: trace
