server:
  port: 8082

spring:
  application.name: bestProduct
  datasource:
    url: jdbc:h2:tcp://localhost:1521/member
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.orm.jdbc.bind: trace

#springdoc swagger
springdoc:
  api-docs:
    path: /docs # ?? path ??

  swagger-ui:
    path: /swagger-ui # ?? path ??
    display-request-duration: true


security.jwt:
  expiration-time: 86400000
  secret-key: secret_key
