server:
  port: 8083

spring:
  application.name: order
  datasource:
    url: jdbc:h2:tcp://localhost:1521/order
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.orm.jdbc.bind: trace

#springdoc swagger
springdoc:
  api-docs:
    path: /docs # ?? path ??

  swagger-ui:
    path: /swagger-ui # ?? path ??
    display-request-duration: true

producers:
  bootstrap-servers: localhost:9092
  topic:
    order:
      cancel: order_cancel
      complete: order_complete
      shipping-info:
        change: shipping_info_change
