server:
  port: 8084

spring:
  application.name: product
  datasource:
    url: jdbc:h2:tcp://localhost:1521/product
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.orm.jdbc.bind: trace

#springdoc swagger
springdoc:
  api-docs:
    path: /docs # ?? path ??

  swagger-ui:
    path: /swagger-ui # ?? path ??
    display-request-duration: true



consumers:
  topic:
    order:
      group-id: order
      cancel: order_cancel

producers:
  topic:
    product:
      tag:
        change: tag_changed
